# Generated by Django 4.0 on 2022-03-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(default=1, max_length=80, verbose_name='Hospital Name'),
            preserve_default=False,
        ),
    ]
