# Generated by Django 4.0 on 2022-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_groups_userprofile_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
