# Generated by Django 4.0 on 2022-03-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='timing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_uid',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('-A', '-A'), ('+A', '+A'), ('-B', '-B'), ('+B', '+B'), ('-AB', '-AB'), ('+AB', '+AB'), ('-O', '-O'), ('+O', '+O')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='patient'),
        ),
    ]
