# Generated by Django 4.0 on 2022-03-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='user-profile'),
            preserve_default=False,
        ),
    ]
