# Generated by Django 4.0 on 2022-03-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_doctor_blood_group_doctor_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient'),
        ),
    ]
