# Generated by Django 4.0 on 2022-03-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_appointment_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
