# Generated by Django 4.0 on 2022-03-15 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_doctor_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of Medicine')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity')),
                ('days', models.CharField(blank=True, max_length=100, null=True, verbose_name='Days')),
                ('time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Time')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('date_created', models.DateField(auto_now=True)),
                ('appointement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='user.appointment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
