# Generated by Django 4.0 on 2022-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='card_status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('V', 'Verified')], max_length=1, null=True),
        ),
    ]
