# Generated by Django 4.0 on 2022-03-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_patient_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_card_exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
