# Generated by Django 4.0 on 2022-03-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_patient_health_card_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approve')], max_length=2, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('no_of_doctor', models.CharField(max_length=100, null=True)),
                ('no_of_beds', models.CharField(max_length=100, null=True)),
                ('foundation_date', models.DateField(null=True)),
                ('timing', models.CharField(max_length=100, null=True)),
                ('owner_name', models.CharField(max_length=100, null=True)),
                ('days', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('biography', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
