# Generated by Django 4.0 on 2022-03-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(null=True)),
                ('a_timing', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approve')], max_length=2, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
