# Generated by Django 4.0 on 2022-04-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_hospital_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('appoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.appointment')),
            ],
        ),
    ]
